name: "Deploy - Hola mundo"

on: push

jobs:
  firts_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["hola", "codigo", "bootcma"]

    steps:
      - name: print mensajes
        run: echo "${{ matrix.message }}"
